# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a94480260874dbbd11ee343bb5630a8489848108e4282b0042e3343c0d46875e4297c5cc0e75526961a82a04c409d0d1d21fae4d4b19e24dcc24f1dea01a3c55

test:
  secret_key_base: 220ebb8c5d035d4f61d5bebb16a84e9716c12c44212864ca876a341f07287c93975b2990a0120cc636602774b82ef6be88e741bab8598e40854958f3de571eac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
